#!/usr/bin/env bash
#
# kaggle-embed-lots.sh — launch TWO balanced, per-RELEASE Kaggle GPU sessions that
# embed the whole corpus CONCURRENTLY (one lot each), then collect + merge their
# output. This is the "go home, come back in ~7h, it's done" path.
#
# Why release-lots (not the per-series campaign): the kernel runs ~50-60 clauses/s on
# 2×T4/fp16, so the full corpus (~2.45M clauses) is ~11-12h on ONE session — it barely
# fits the 12h cap and uses a single session at a time. Splitting the RELEASES into two
# near-equal lots (≈1.223M clauses each, balanced to 0.065% by a greedy LPT on the
# kernel's own release_totals) lets two sessions run side by side, so each lot is
# ~6h and the wall-clock for the whole corpus is ~6h. Each lot also fits comfortably
# inside ONE session, so no cross-session chaining is even required — though the
# per-lot resume Dataset still makes a killed lot resumable (recent-first ordering
# leaves the newest releases done first).
#
# Posture (matches "creds never leave the laptop"): the kernel carries NO credentials.
# THIS driver — running where the kaggle token lives — pushes the kernels, and later
# pulls their /kaggle/working output and (optionally) versions a resume Dataset. The
# heavy ~6h compute runs UNATTENDED in the Kaggle cloud: once `push` returns, the
# laptop can close. Kaggle auto-saves each kernel's working dir as its output, so the
# embedded DBs are safe in the cloud and `collect` retrieves them on your return.
#
# Auth: kaggle CLI 2.x reads its token from KAGGLE_API_TOKEN or ~/.kaggle/access_token.
# This driver only needs KAGGLE_USER (your handle) to namespace the slugs.
#
# Usage:
#   KAGGLE_USER=<handle> scripts/kaggle-embed-lots.sh push        # stage + push BOTH lots (2 concurrent sessions)
#   KAGGLE_USER=<handle> scripts/kaggle-embed-lots.sh status      # terminal/running state of both kernels
#   KAGGLE_USER=<handle> scripts/kaggle-embed-lots.sh collect     # pull both outputs into the stage dir
#   KAGGLE_USER=<handle> scripts/kaggle-embed-lots.sh merge OUT   # merge the two collected lot DBs into OUT
#
# Env:
#   KAGGLE_USER       Kaggle handle (required; namespaces slugs)
#   BRANCH            repo branch the kernel clones (default: current git branch)
#   EMBED_PRECISION   fp16 (default; ~2-6x on T4 Tensor Cores) | fp32
#   CHECKPOINT_EVERY  durable-checkpoint cadence (default 2000)
#   STAGE             staging dir (default .kaggle-lots, gitignored)
#   LOT_A / LOT_B     override the release sets (comma-separated). Defaults below are
#                     the balanced split from the kernel's whole-corpus release_totals.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STAGE="${STAGE:-$ROOT/.kaggle-lots}"
PRECISION="${EMBED_PRECISION:-fp16}"
CHECKPOINT_EVERY="${CHECKPOINT_EVERY:-2000}"
BRANCH="${BRANCH:-$(git -C "$ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null || echo main)}"

# Balanced per-RELEASE lots (greedy LPT on the kernel's whole-corpus release_totals):
#   Lot A = 1,223,947 clauses   Lot B = 1,222,353 clauses   (Δ = 1,594 = 0.065%)
# Floor is Rel-99 (the LOWEST recency ordinal) so the slice keeps EVERY listed release;
# selection is the explicit set, not a range — non-contiguous by design.
LOT_A="${LOT_A:-Rel-19,Rel-16,Rel-15,Rel-12,Rel-10,Rel-9,Rel-7,Rel-4,Rel-20}"
LOT_B="${LOT_B:-Rel-18,Rel-17,Rel-14,Rel-13,Rel-11,Rel-8,Rel-6,Rel-5,Rel-99}"

die() { echo "error: $*" >&2; exit 1; }
log() { echo "[kaggle-lots] $*"; }

require_cli() {
  command -v kaggle >/dev/null 2>&1 || die "the 'kaggle' CLI is not installed (pip install kaggle)"
  [ -n "${KAGGLE_USER:-}" ] || die "set KAGGLE_USER to your Kaggle handle (namespaces the slugs)"
}

kernel_slug() { echo "${KAGGLE_USER}/3gpp-embed-lot$1"; }            # $1 = A|B
state_slug()  {                                                      # precision-scoped, like the campaign
  if [ "$PRECISION" = fp32 ]; then echo "${KAGGLE_USER}/3gpp-embedded-lot$1"
  else echo "${KAGGLE_USER}/3gpp-embedded-lot$1-$PRECISION"; fi
}

# stage_kernel LOT RELEASES DIR — write the per-lot PYTHON code_file: a tiny
# os.environ.setdefault config header (LOT/EMBED_RELEASES/floor/precision/branch; NO
# creds) followed by the shared native kernel body, plus a kernel-metadata.json. No
# dataset_sources on first push: the kernel fresh-slices the lot from the published
# `latest` lexical DB (mounting a not-yet-existing resume Dataset is what Kaggle
# rejects). A later run can resume by mounting state_slug once it holds partial state.
stage_kernel() {
  local lot="$1" rels="$2" dir="$3"; mkdir -p "$dir"
  {
    echo "# generated by kaggle-embed-lots.sh — per-lot config, no credentials"
    echo "import os"
    echo "os.environ.setdefault('LOT', '$lot')"
    echo "os.environ.setdefault('EMBED_RELEASES', '$rels')"
    echo "os.environ.setdefault('EMBED_FLOOR', 'Rel-99')"
    echo "os.environ.setdefault('BRANCH', '$BRANCH')"
    echo "os.environ.setdefault('CHECKPOINT_EVERY', '$CHECKPOINT_EVERY')"
    echo "os.environ.setdefault('EMBED_PRECISION', '$PRECISION')"
    echo "os.environ.setdefault('EMBED_STATE_DS', '$(state_slug "$lot")')"
    cat "$ROOT/scripts/kaggle/kernel-embed.py"
  } > "$dir/kernel.py"
  local sources=""
  if [ -f "$STAGE/state-$lot/3gpp-embedded.duckdb" ]; then
    sources="\"$(state_slug "$lot")\""
  fi
  printf '{\n "id": "%s",\n "title": "3gpp embed lot%s",\n "code_file": "kernel.py",\n "language": "python",\n "kernel_type": "script",\n "is_private": true,\n "enable_gpu": true,\n "enable_internet": true,\n "dataset_sources": [%s],\n "competition_sources": [],\n "kernel_sources": []\n}\n' \
    "$(kernel_slug "$lot")" "$lot" "$sources" > "$dir/kernel-metadata.json"
}

push_one() {
  local lot="$1" rels="$2"; local dir="$STAGE/kernel-$lot"
  stage_kernel "$lot" "$rels" "$dir"
  log "lot $lot: push  releases=$rels  precision=$PRECISION  branch=$BRANCH"
  local out
  if out="$(kaggle kernels push -p "$dir" 2>&1)"; then
    log "lot $lot: pushed -> $(kernel_slug "$lot")  ($out)"
  else
    die "lot $lot: push failed: $out"
  fi
}

cmd_push() {
  require_cli
  # Warn (don't block) if the kernel's BRANCH isn't on the remote yet: the kernel
  # clones REPO@BRANCH from GitHub, so unpushed local commits won't be seen.
  if ! git -C "$ROOT" ls-remote --exit-code origin "refs/heads/$BRANCH" >/dev/null 2>&1; then
    log "WARNING: branch '$BRANCH' not found on origin — the kernel clones from GitHub; push it first."
  fi
  push_one A "$LOT_A"
  push_one B "$LOT_B"
  log "both lots pushed — 2 concurrent GPU sessions are now queued/running in the Kaggle cloud."
  log "you can close the laptop. check later with: KAGGLE_USER=$KAGGLE_USER $0 status"
}

cmd_status() {
  require_cli
  for lot in A B; do
    printf '[kaggle-lots] lot %s: ' "$lot"
    kaggle kernels status "$(kernel_slug "$lot")" 2>&1 | head -1
  done
}

cmd_collect() {
  require_cli
  for lot in A B; do
    local out="$STAGE/out-$lot"; mkdir -p "$out"
    log "lot $lot: pulling kernel output -> $out"
    kaggle kernels output "$(kernel_slug "$lot")" -p "$out" >/dev/null 2>&1 || log "lot $lot: no output yet"
    [ -f "$out/RESULT.txt" ] && grep -E 'step=OK|complete=1|FAIL=|embedded=|throughput=' "$out/RESULT.txt" | sed "s/^/[lot $lot] /" || true
  done
  log "collected. merge with: $0 merge data/3gpp-embedded.duckdb"
}

# cmd_merge OUT — fuse the two collected lot DBs (release-disjoint shards) into OUT
# via cmd/merge, then the usual post-merge FTS/HNSW rebuild applies. Lots partition
# the corpus by release, so the union is the full embedded corpus with no overlap.
cmd_merge() {
  local out="${1:?usage: $0 merge OUT_DB}"
  local a="$STAGE/out-A/3gpp-embedded.duckdb" b="$STAGE/out-B/3gpp-embedded.duckdb"
  [ -f "$a" ] || die "missing lot A DB ($a) — run '$0 collect' first"
  [ -f "$b" ] || die "missing lot B DB ($b) — run '$0 collect' first"
  log "merging lot A + lot B -> $out"
  go -C "$ROOT" run ./cmd/merge --out "$out" "$a" "$b" \
    || die "merge failed (check cmd/merge flags with: go run ./cmd/merge -h)"
  log "merged -> $out"
}

case "${1:-}" in
  push)    cmd_push ;;
  status)  cmd_status ;;
  collect) cmd_collect ;;
  merge)   shift; cmd_merge "$@" ;;
  *) cat >&2 <<EOF
usage: KAGGLE_USER=<handle> $0 {push|status|collect|merge OUT}
  push     stage + push BOTH balanced release-lots as 2 concurrent Kaggle GPU sessions
  status   show each kernel's running/terminal state
  collect  pull both kernels' /kaggle/working output into $STAGE
  merge    fuse the two collected lot DBs into OUT (release-disjoint shards)

  Lot A: $LOT_A
  Lot B: $LOT_B
EOF
     exit 2 ;;
esac
