#!/usr/bin/env bash
#
# kaggle-rel15-20.sh — operator driver for the sharded, RESUMABLE embed campaign.
# Generalises kaggle-embed-poc.sh from one series to the whole corpus: one Kaggle
# GPU kernel per SERIES, each resuming across the 12h cap via its own embedded-state
# Dataset, with retries and skip-when-complete.
#
# Posture (matches the project's "creds never leave the laptop" rule): the kernel
# itself carries NO credentials — it embeds and writes /kaggle/working/3gpp-embedded.duckdb;
# THIS driver (running on your box, where ~/.kaggle/kaggle.json lives) pulls that
# output and runs `kaggle datasets version` to publish the resume state. The kernel's
# optional self-version tail only fires if you instead attach Kaggle Secrets to it.
#
# Kaggle is a best-effort MANUAL acceleration path, NOT a CI base (12h ephemeral
# sessions, ~30 GPU-h/week, throttling, ToS). Run this locally or from a trusted
# runner that holds the kaggle creds.
#
# Usage:
#   KAGGLE_USER=<handle> scripts/kaggle-rel15-20.sh one 33      # one series end-to-end
#   KAGGLE_USER=<handle> scripts/kaggle-rel15-20.sh all         # every series in SERIES_LIST
#   KAGGLE_USER=<handle> scripts/kaggle-rel15-20.sh status 33
#
# Env:
#   KAGGLE_USER       Kaggle handle (required; namespaces slugs)
#   SERIES_LIST       space-separated series, priority order
#                     (default: core-network first "23 24 29 33 38 21 22 25 26 27 28 31 32 35 36 37")
#   EMBED_FLOOR       release floor (default Rel-15)
#   BRANCH            repo branch the kernel clones (default feat/embed-maximization)
#   CHECKPOINT_EVERY  durable-checkpoint cadence (default 2000)
#   MAX_RETRIES       per-series ERROR retries (default 3)
#   STAGE             staging dir (default .kaggle-campaign, gitignored)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STAGE="${STAGE:-$ROOT/.kaggle-campaign}"
EMBED_FLOOR="${EMBED_FLOOR:-Rel-17}"
BRANCH="${BRANCH:-main}"
CHECKPOINT_EVERY="${CHECKPOINT_EVERY:-2000}"
MAX_RETRIES="${MAX_RETRIES:-3}"
SERIES_LIST="${SERIES_LIST:-23 24 29 33 38 21 22 25 26 27 28 31 32 35 36 37}"

die() { echo "error: $*" >&2; exit 1; }
log() { echo "[kaggle-campaign] $*"; }

require_cli() {
  command -v kaggle >/dev/null 2>&1 || die "the 'kaggle' CLI is not installed (pip install kaggle)"
  [ -n "${KAGGLE_USER:-}" ] || die "set KAGGLE_USER to your Kaggle handle (namespaces the slugs)"
}

kernel_slug()  { echo "${KAGGLE_USER}/3gpp-embed-s$1"; }
state_slug()   { echo "${KAGGLE_USER}/3gpp-embedded-s$1"; }

# NOTE: there is intentionally NO pre-created empty resume Dataset. Mounting a
# freshly-created empty dataset is what Kaggle's `kernels push` rejected on the
# first run; instead the resume Dataset is created lazily by `version_state` on
# the first publish (create-or-version), and `stage_kernel` mounts it only once it
# holds embedded state. The first run needs no mount — the kernel fresh-slices.

# stage_kernel SERIES DIR — write the per-series PYTHON code_file (Kaggle kernels
# only accept language python/r/rmarkdown, never bash): a tiny os.environ.setdefault
# config header (SERIES/floor/state-dataset; NO creds) followed by the shared native
# Python kernel body, plus kernel-metadata.json mounting this series' resume dataset.
stage_kernel() {
  local s="$1" dir="$2"; mkdir -p "$dir"
  {
    echo "# generated by kaggle-rel15-20.sh — per-series config, no credentials"
    echo "import os"
    echo "os.environ.setdefault('SERIES', '$s')"
    echo "os.environ.setdefault('EMBED_FLOOR', '$EMBED_FLOOR')"
    echo "os.environ.setdefault('BRANCH', '$BRANCH')"
    echo "os.environ.setdefault('CHECKPOINT_EVERY', '$CHECKPOINT_EVERY')"
    echo "os.environ.setdefault('EMBED_STATE_DS', '$(state_slug "$s")')"
    cat "$ROOT/scripts/kaggle/kernel-embed.py"
  } > "$dir/kernel.py"
  # Mount the resume Dataset ONLY once it actually holds embedded state. On the very
  # first run nothing is published yet; mounting a freshly-created empty dataset is
  # what Kaggle's push rejects — and it isn't needed, the kernel does a fresh slice
  # when no RESUME_DB is present. `recover_orphan` repopulates state-$s from Kaggle
  # before each push, so this local file is a faithful proxy for "resume published".
  local sources=""
  if [ -f "$STAGE/state-$s/3gpp-embedded.duckdb" ]; then
    sources="\"$(state_slug "$s")\""
  fi
  printf '{\n "id": "%s",\n "title": "3gpp embed s%s",\n "code_file": "kernel.py",\n "language": "python",\n "kernel_type": "script",\n "is_private": true,\n "enable_gpu": true,\n "enable_internet": true,\n "dataset_sources": [%s],\n "competition_sources": [],\n "kernel_sources": []\n}\n' \
    "$(kernel_slug "$s")" "$s" "$sources" > "$dir/kernel-metadata.json"
}

# poll_kernel SERIES — block until the kernel reaches a terminal state. Echoes
# complete | error | cancel (the CLI exit code is unreliable, so parse the string).
poll_kernel() {
  local s="$1" slug out; slug="$(kernel_slug "$s")"
  while :; do
    out="$(kaggle kernels status "$slug" 2>&1 || true)"
    case "$out" in
      *complete*|*COMPLETE*) echo complete; return 0 ;;
      *error*|*ERROR*)       echo error;    return 0 ;;
      *cancel*|*CANCEL*)     echo cancel;   return 0 ;;
    esac
    sleep 30
  done
}

# series_complete SERIES — true when the pulled output reports null_at_floor==0.
# (Reads the RESULT marker the kernel writes; absent output → not complete.)
series_complete() {
  local s="$1"; local f="$STAGE/out-$s/RESULT.txt"
  [ -f "$f" ] && grep -q 'complete=1' "$f"
}

# version_state SERIES — publish the pulled embedded DB back to the resume dataset
# FROM THE LAPTOP (where creds live). Next run mounts it and resumes.
version_state() {
  local s="$1"; local out="$STAGE/out-$s" db
  db="$(find "$out" -name '3gpp-embedded.duckdb' | head -1)"
  [ -n "$db" ] || { log "series $s: no embedded DB in output — skipping version"; return 0; }
  local d="$STAGE/state-$s"; mkdir -p "$d"; cp "$db" "$d/3gpp-embedded.duckdb"
  printf '{\n "title": "3gpp-embedded-s%s",\n "id": "%s",\n "licenses": [{"name": "CC0-1.0"}]\n}\n' \
    "$s" "$(state_slug "$s")" > "$d/dataset-metadata.json"
  log "series $s: versioning resume state -> $(state_slug "$s")"
  # Create-or-version: the resume Dataset is no longer pre-created empty (that empty
  # mount is exactly what Kaggle rejected on the first push), so the FIRST publish
  # must `create`; later publishes `version`. Distinguish by querying its status.
  if kaggle datasets status "$(state_slug "$s")" >/dev/null 2>&1; then
    kaggle datasets version -p "$d" -m "series=$s $(date -u +%FT%TZ)" --dir-mode zip >/dev/null 2>&1 \
      || log "series $s: dataset version failed (see kaggle logs)"
  else
    kaggle datasets create -p "$d" --dir-mode zip >/dev/null 2>&1 \
      || log "series $s: dataset create failed (see kaggle logs)"
  fi
}

# recover_orphan SERIES — DURABILITY KEYSTONE. Pull whatever the kernel left as its
# LAST output and promote any partial embedded DB into the resume Dataset, BEFORE we
# push again. This recovers progress orphaned when a prior driver process was killed
# (e.g. the GitHub runner's 6h cap) AFTER the Kaggle kernel finished its work but
# BEFORE the driver could version it: the kernel's `timeout 39000` makes it exit
# cleanly under Kaggle's 12h cap, so Kaggle auto-saves /kaggle/working as the kernel
# output, and this step pulls it forward so the next kernel mounts it and resumes via
# embedding_hash. No credentials ever live in the kernel — only the driver versions.
recover_orphan() {
  local s="$1"
  mkdir -p "$STAGE/out-$s"
  kaggle kernels output "$(kernel_slug "$s")" -p "$STAGE/out-$s" >/dev/null 2>&1 || true
  version_state "$s"   # no-op when there is no prior output; promotes a partial otherwise
}

# run_one SERIES — recover any orphaned partial, then push → poll → pull → version,
# retrying on ERROR, until the series reports complete or retries are exhausted.
run_one() {
  require_cli
  local s="$1" attempt=0; local dir="$STAGE/kernel-$s"
  recover_orphan "$s"    # resume a partial left by a killed prior run (GH 6h cap, etc.)
  while [ "$attempt" -le "$MAX_RETRIES" ]; do
    attempt=$((attempt+1))
    log "series $s: attempt $attempt/$((MAX_RETRIES+1)) — push"
    stage_kernel "$s" "$dir"
    # Capture push output so a failure surfaces its REASON (auth, invalid metadata,
    # missing/unready dataset source). MUST be done as the `if` condition: under
    # `set -e`, a bare `v=$(cmd)` assignment whose substitution fails aborts the whole
    # script *before* we can read $? — which is why earlier the driver vanished right
    # after "attempt 1 — push" with no reason logged. As an `if` condition, set -e is
    # suppressed and $? is the push's real exit code.
    local push_out push_rc
    if push_out="$(kaggle kernels push -p "$dir" 2>&1)"; then
      push_rc=0
    else
      push_rc=$?
      log "series $s: push failed (rc=$push_rc): $(printf '%s' "$push_out" | tr '\n' ' ' | tail -c 400)"
      sleep 15; continue
    fi
    local state; state="$(poll_kernel "$s")"
    mkdir -p "$STAGE/out-$s"
    kaggle kernels output "$(kernel_slug "$s")" -p "$STAGE/out-$s" >/dev/null 2>&1 || true
    version_state "$s"
    if series_complete "$s"; then
      log "series $s: COMPLETE (null_at_floor=0)"; return 0
    fi
    case "$state" in
      complete) log "series $s: kernel complete but partial (time budget) — relaunching to continue" ;;
      error|cancel) log "series $s: kernel $state — retrying" ;;
    esac
  done
  log "series $s: still incomplete after $((MAX_RETRIES+1)) attempts — re-run 'one $s' to continue (resume is lossless)"
  return 1
}

# run_all — drive every series in priority order. zsh-safe: iterate via a
# while-read over a newline-split list, never `for x in $SERIES_LIST`.
run_all() {
  require_cli
  local rc=0
  printf '%s\n' "$SERIES_LIST" | tr ' ' '\n' | while IFS= read -r s; do
    [ -n "$s" ] || continue
    run_one "$s" || rc=1
  done
  return "$rc"
}

case "${1:-}" in
  one)    [ -n "${2:-}" ] || die "usage: $0 one <series>"; run_one "$2" ;;
  all)    run_all ;;
  status) require_cli; [ -n "${2:-}" ] || die "usage: $0 status <series>"; kaggle kernels status "$(kernel_slug "$2")" ;;
  *) echo "usage: $0 {one <series>|all|status <series>}" >&2; exit 2 ;;
esac
